# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672bc74915a4d76496a571d086caed4a05d6c78caba08ca877fff19690828a0d3f3dc82ffd9bb35c29dade8f873350075432ae83845b8ffbca15710b91f17662

test:
  secret_key_base: 129cf93f2a0298c6fcd667459fa312640999b49956c0cb3d8208f144704faecc63bcea1c569dd64c972840e42c89570bd187d1d880757495fe255f964a277d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
